[package]
name = "ontrack"
version = "0.0.1"
authors = ["Pete Hayes <pete@hayes.id.au>"]

[dependencies]
ears = "0.5"
error-chain = "0.11"
serde = "1.0"
serde_derive = "1.0"
termion = "1.5"
toml = "0.4"
